#+title: reviewgen.el
#+author: Naoya Yamashita

[[https://github.com/conao3/reviewgen.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/reviewgen.el.png]]
[[https://github.com/conao3/reviewgen.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/reviewgen.el.svg?style=flat-square]]
[[https://github.com/conao3/reviewgen.el/releases][https://img.shields.io/github/tag/conao3/reviewgen.el.svg?style=flat-square]]
[[https://github.com/conao3/reviewgen.el/actions][https://github.com/conao3/reviewgen.el/workflows/Main%20workflow/badge.svg]]

* Overview

reviewgen.el is an Emacs package that helps you generate review comments from prepared typical phrases. It streamlines the code review process by providing quick access to commonly used feedback templates.

* Requirements

- Emacs 25.1 or later

* Installation

** Using leaf (recommended)

#+begin_src emacs-lisp
(leaf reviewgen
  :ensure t)
#+end_src

** Using use-package

#+begin_src emacs-lisp
(use-package reviewgen
  :ensure t)
#+end_src

** Manual Installation

Clone this repository and add it to your load path:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/reviewgen.el")
(require 'reviewgen)
#+end_src

* Usage

After installation, you can use reviewgen to quickly insert review comments into your buffers. The package provides templates for common review scenarios.

* Customization

You can customize reviewgen through the customization interface:

#+begin_src emacs-lisp
M-x customize-group RET reviewgen RET
#+end_src

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests.

** Development Setup

1. Install [[https://github.com/cask/cask][Cask]] for dependency management:

   #+begin_src shell
   # macOS
   brew install cask

   # Manual installation
   git clone https://github.com/cask/cask ~/.cask
   export PATH="$HOME/.cask/bin:$PATH"
   #+end_src

2. Clone the repository and install dependencies:

   #+begin_src shell
   git clone https://github.com/conao3/reviewgen.el
   cd reviewgen.el
   make
   #+end_src

** Running Tests

#+begin_src shell
make test
#+end_src

** Submitting Changes

1. Create a feature branch from =master=
2. Make your changes and add tests if applicable
3. Run =make test= to ensure all tests pass
4. Submit a pull request

* License

This project is licensed under the GNU General Public License v3.0. See the [[https://github.com/conao3/reviewgen.el/blob/master/LICENSE][LICENSE]] file for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
